server:
  port: 8089 # Port di mana service ini berjalan

spring:
  application:
    name: anggota-service # Nama unik untuk service ini

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Alamat server Eureka
