pipeline {
    agent any

    stages {
        stage('Ambil Kode') {
            steps {
                // Pastikan URL repo kamu benar
                git branch: 'main', url: 'https://github.com/HanifaRamadhani-29/MIcroservices_praktek'
            }
        }

        stage('Build & Run Microservices') {
            steps {
                echo 'Sedang masuk ke folder pustaka-jenkin...'
                // GANTI tugas-pustaka MENJADI pustaka-jenkin
                dir('pustaka-jenkin') {
                    sh 'docker-compose up -d --build'
                }
            }
        }

        stage('Verifikasi') {
            steps {
                echo 'Cek container yang sedang jalan:'
                sh 'docker ps'
            }
        }
    }
}