pipeline {
    agent any

    stages {
        stage('Ambil Kode') {
            steps {
                git branch: 'main', url: 'https://github.com/HanifaRamadhani-29/MIcroservices_praktek'
            }
        }

        stage('Build & Run Microservices') {
            steps {
                dir('pustaka-jenkin') {
                    echo 'Membersihkan folder palsu dan container lama...'
                    // SCRIPT SAKTI: Cek jika prometheus.yml itu folder, maka hapus!
                    sh '''
                    if [ -d "prometheus.yml" ]; then rm -rf prometheus.yml; fi
                    if [ -d "loki-config.yml" ]; then rm -rf loki-config.yml; fi
                    git checkout prometheus.yml loki-config.yml || echo "File aslinya belum ada di Git"
                    '''
                    
                    sh 'docker-compose down'
                    sh 'docker-compose up -d --build'
                }
            }
        }

        stage('Verifikasi') {
            steps {
                sh 'docker ps'
            }
        }
    }
}